### ISSUE TITLE
How to set the round I want to run for data augmentation?

### ISSUE THREAD

**Issue by TransformersWsz** [salesforce/coco-dst#3]
Thank you for providing the augmentation training file `8times_coco-vs_rare_out_domain_train_classifier_change_add-2-max-3_drop-1_seed_0.json`. However, I can't find how to set the round to run for data augmentation in `run_genn.py` . Could you offer more details?

**Comment by semihyavuzz** [comment]
@TransformersWsz You can set it [here](https://github.com/salesforce/coco-dst/blob/ae9b5de90851fc8731d99a7e1c3cf4819470c14a/coco-dst/run_gene.py#L267), which is under `multi_fold_coco_aug` branch.
